config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get '/search', to: 'posts#search'
  post '/comments/:comment_id/replies', to: 'replies#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show, :edit, :update]

  resources :conversations, only: [:create, :index, :show, :destroy]

  resources :posts do
    resources :comments, only: [:create]
    resources :ratings, only: [:create, :index, :show]
  end

  resources :conversations, only:[:index, :show] do
    resources :messages, only: :create
  end

  resources :replies, only: [:create]

  # not working: have a root user path, as the user has to be read from params
  # as :user do
  #   get 'profiles/:id', :to => 'profiles#show', :as => :user_root # Rails 3
  # end

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  has_many :messages, dependent: :destroy
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController


  def create
    sender = current_user
    post = Post.find(params[:post_id])
    receiver = post.user
    conversation = Conversation.new(sender: sender, receiver: receiver)
    authorize conversation
    if Conversation.find_by(sender: sender, receiver: receiver) || Conversation.find_by(sender: receiver, receiver: sender)
      redirect_to "/conversations/#sidebar"
    else
      if conversation.save!
        redirect_to "/conversations/"
      end
    end

  end

  def index
    @conversations = policy_scope(Conversation)
    @message = Message.new
    # convs_ids = []
    # @conversations.each do |conv|
    #   convs_ids << conv.id
    # end
    respond_to do |format|
      format.html
      format.json { render json: { conversations: @conversations } }
    end
  end

  def show
    @conversation = Conversation.find(params[:id])
    current_user.update(conversation_channel: @conversation.id)
    @message = Message.new
    authorize @conversation

    if current_user == @conversation.sender 
      @conversation.sender_notifications  = 0 
    else 
      @conversation.receiver_notifications = 0 
    end 
    @conversation.save
    # authorize @messages
    ################# for unseen notifications #################
    # if @conversation.sender == current_user
    #   receiver_unseen_msgs = conversation.messages.where(user: conversation.receiver, seen: false)
    #   receiver_unseen_msgs.each do |msg|
    #     msg.update(seen: true)
    #   end
    # else
    #   sender_unseen_msgs = conversation.messages.where(user: conversation.sender, seen: false)
    #   sender_unseen_msgs.each do |msg|
    #     msg.update(seen: true)
    #   end
    # end

  end

  def destroy
  end

  private

  def conversation_params
    params.require(:conversation).permit(:sender, :receiver)
  end
end

app/views/conversations/_conversation.html.erb
<% current_user.update(conversation_channel: conversation.id)  %>
<div id="messages" data-conversation-id="<%= conversation.id %>">
  <div class="message-container" id="message-0" style="display: none"></div>

  <% conversation.messages.each do |message| %>
    <%= render "messages/message", message: message %>
  <% end %>
</div>

app/views/conversations/_send.html.erb
<span id="send">
  <%= simple_form_for [ conversation, message ], remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: "Message" %>
  <% end %>
</span>

app/views/conversations/index.html.erb
<%# current_user.update(conversation_channel: 0)  %>
<div class="kontainer">
  <div data-controller="conversation">
    <div class="wrapper">
      <!-- Sidebar -->
      <div id="sidebar-container">
        <nav id="sidebar">
          <div class="sidebar-header">
            <h3>Conversations</h3>
          </div>
          <% if @conversations.count > 0 %>

            <ul class="list-unstyled components">
                <% @conversations.each do |conversation| %>
                  <% if conversation.sender == current_user %>
                        <li data-action="click->conversation#refresh" data-id="<%= conversation.id %>"  >
                            <a href=<%= profile_path(conversation.receiver)%>><%= cl_image_tag conversation.receiver.prof_pic.key, class: "avatar" %></a>
                            <%= link_to conversation.receiver.nickname, conversation_path(conversation), remote: true, class: "clickble-name" %>
                            <% if conversation.sender_notifications > 0 %>
                              <div id="<%= conversation.receiver.nickname %>" class="chat-badge badge"><%= conversation.sender_notifications %></div>
                            <% else %>
                              <div id="<%= conversation.receiver.nickname %>" class="chat-badge badge" style="display: none;">0</div>
                            <% end %>

                        </li>
                  <% else %>
                    <li data-action="click->conversation#refresh" data-id="<%= conversation.id %>">
                        <a href=<%= profile_path(conversation.sender)%>><%= cl_image_tag conversation.sender.prof_pic.key, class: "avatar" %></a>
                        <%= link_to conversation.sender.nickname, conversation_path(conversation), remote: true, class: "clickble-name"%>

                        <% if conversation.receiver_notifications > 0 %>
                          <div id="<%= conversation.sender.nickname %>" class="chat-badge badge"><%= conversation.receiver_notifications  %></div>
                        <% else %>
                            <div id="<%= conversation.sender.nickname %>" class="chat-badge badge" style="display: none;">0</div>
                        <% end %>
                    </li>
                  <% end %>
                <% end %>
            </ul>

          <% end %>
        </nav>
      </div>

      <div id="nickname" style="display: none"><%= current_user.nickname %></div>

      <div class="chat">
        <% if @conversations.count > 0 %>

            <div class="conversation" data-conversation-target="conversationcon">
              <%#= render 'conversation', {conversation: @conversations.last}%>
            </div>
              
            <span class="sendfield" id="chat-text"  data-conversation-target="sendcon">
              <%#= render 'send', {conversation: @conversations.last, message: @message }%>
            </span>

        <% else %>
          <div><h4>You dont have any conversations yet.</h4></div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>

  
  // left << this user's msg   other user's msg >> right
  function display(){
    nickname = document.getElementById('nickname').innerText
    document.querySelectorAll(".message-container").forEach(elm =>{
      if (elm.children[0] !== undefined){
        if(elm.children[0].children[0].children[0].innerHTML !== nickname){
          if (elm.children[0].style.float !== "right"){
            elm.children[0].style.float = "left"
          }
          
        }
      } 
    })
  }

  display()

</script>


<style>
body{
   overflow-y: unset;
}
</style>

app/views/conversations/show.html.erb
<% current_user.update(conversation_channel: @conversation.id)  %>
<div id="messages" data-conversation-id="<%= @conversation.id %>">
  <div class="message-container" id="message-0" style="display: none"></div>

  <% @conversation.messages.each do |message| %>
    <%= render "messages/message", message: message %>
  <% end %>
</div>



<span id="send">
  
    <%= simple_form_for [ @conversation, @message ] , html: { autocomplete: 'off' } do |f| %>
    <%# <div style="display:flex;flex-direction:row"> %>
      <%= f.input :content, label: false, placeholder: "Message", remote: true %>
      
    <% end %>
  <%# </div> %>
</span>