config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get '/search', to: 'posts#search'
  post '/comments/:comment_id/replies', to: 'replies#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show, :edit, :update]

  resources :conversations, only: [:create, :index, :show, :destroy]

  resources :posts do
    resources :comments, only: [:create]
    resources :ratings, only: [:create, :index, :show]
  end

  resources :conversations, only:[:index, :show] do
    resources :messages, only: :create
  end

  resources :replies, only: [:create]

  # not working: have a root user path, as the user has to be read from params
  # as :user do
  #   get 'profiles/:id', :to => 'profiles#show', :as => :user_root # Rails 3
  # end

end

app/views/shared/_banner.html.erb
<div class="banner">


    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
            <h2 class="banner-slogan">"Increase your knowledge, reduce your foot print, <br> improve our future."</h2>
            <p class="banner-sign">~ The Ecosystem crew</p>
        </div>
        <div class="carousel-item">
          <h2 class="banner-slogan">“What we are doing to the forests of the world is but a mirror reflection <br> of what we are doing to ourselves.”</h2>
          <p class="banner-sign">~ Mahatma Gandhi</p>
        </div>
        <div class="carousel-item">
          <h2 class="banner-slogan">“I only feel angry when I see people throwing away things <br> we could use.”</h2>
          <p class="banner-sign">~ Mother Teresa</p>
        </div>
        <div class="carousel-item">
          <h2 class="banner-slogan">“Progress is impossible without change, and those who cannot change their minds <br> cannot change anything.”</h2>
          <p class="banner-sign">~ George Bernard Shaw</p>
        </div>
        <div class="carousel-item">
          <h2 class="banner-slogan">“Never doubt that a small group of thoughtful, committed citizens can change the world; <br> indeed, it is the only thing that ever has.”</h2>
          <p class="banner-sign">~ Margaret Mead</p>
        </div>
      </div>
    </div>

</div>

app/views/shared/_create_post.html.erb
<div class="post-box">
  <%= simple_form_for @post do |f| %>
    <div class="field">
      <h3><%= "Title" %></h3>
      <%= f.input :title, label: false %>

      <h3><%= "Category" %></h3>
      <%= f.input :category, collection: ["hack", "don't", "project"], label: false %>

      <h3><%= "Topics (what is this post about?)" %></h3>
      <%= f.input :topic, label: false %>

      <% if @post.photos.attached? %>
        <h3><%= "Preview Picture" %></h3>
        <%= cl_image_tag @post.photos.last.key, height: 200 %><br>
      <% end %>

      <h3><%= "Expectations of Your Idea:" %></h3>
      <%= f.input :expect_co2, collection: ['low', 'moderate', 'medium', 'high', 'very high'], label: "How high will be your Co2 savings?" %>
      <%= f.input :expect_waste, collection: ['low', 'moderate', 'medium', 'high', 'very high'], label: "Your savings on waste?" %>
      <%= f.input :expect_resources, collection: ['low', 'moderate', 'medium', 'high', 'very high'], label: "Your savings on resources?" %>
      <%= f.input :expect_diyeffort, collection: ['low', 'moderate', 'medium', 'high', 'very high'], label: "How high do you estimate the effort to realise these goals? ('DIY effort')" %>
      <%= f.input :expect_ecocost, collection: ['low', 'moderate', 'medium', 'high', 'very high'], label: "How high do you estimate counter effects (for ex. you might need resources to clean reusable packaging)?" %>
      <h3><%= "Gallery Image" %></h3>
      <%= f.input :photos, as: :file, label: false %>
      <h3><%= "Post Text" %></h3>
      <%= f.input :rich_body, as: :rich_text_area, label: false %>
      <%= f.button :submit, "Send!", class: 'btn btn-large' %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">

    <div class="footer-bottom d-flex">

      <p>© 2021 the-ecosystem.net</p>

      <div class="social d-flex">
        <i class="fab fa-instagram-square"></i>
        <i class="fab fa-google-plus-square"></i>
        <i class="fab fa-pinterest-square"></i>
        <i class="fab fa-instagram-square"></i>
        <i class="fab fa-facebook-square"></i>
        <i class="fab fa-twitter-square"></i>
      </div>

    </div>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon nav-content sticky">
  <span>
    <div class="navbar-brand">
      <%= link_to root_path do %>
        <%= image_tag("logo.png") %>
        <h4>The Ecosystem |</h4>
      <% end %>
    </div>
    <span>
      <strong>
        <%= link_to "about us", root_path, id: "about-us" %>
      </strong>
      <span>&#x1F4A1;</span>
    </span>
  </span>




  <div class="search-log">
    <div id="searches">
      <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control nav-search", placeholder: "Find your solution!" %>
      <% end %>

      <div class="middle-links nav-item dropdown merge-bar">


          <%= link_to "Top Posts", search_path, class: "dropdown-toggle", id: "searchDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>



          <div class="dropdown-menu dropdown-menu-right drop-nav" aria-labelledby="searchDropdown">



            <%= link_to "Top Rated", search_path(:query => "", :category => "", :ratings => "rating_avg"), class: "dropdown-item" %>
            <%= link_to "Saving Co2", search_path(:query => "", :category => "", :ratings => "rating_co2"), class: "dropdown-item" %>
            <%= link_to "Saving Resources", search_path(:query => "", :category => "", :ratings => "rating_resources"), class: "dropdown-item" %>
            <%= link_to "Saving Waste", search_path(:query => "", :category => "", :ratings => "rating_waste"), class: "dropdown-item" %>
            <%= link_to "Low Effort", search_path(:query => "", :category => "", :ratings => "rating_diyeffort"), class: "dropdown-item" %>
            <%= link_to "Low Ecocost", search_path(:query => "", :category => "", :ratings => "rating_ecocost"), class: "dropdown-item" %>
            <%= link_to "Latest", search_path(:query => "", :category => "", :ratings => "created_at"), class: "dropdown-item" %>
          </div>



      </div>
    </div>

      <%= link_to new_post_path do %>
      <i class="fas fa-file-medical create-post nav-item"></i>
      <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% convs_sender = current_user.conversations_as_sender %>
        <% convs_receiver = current_user.conversations_as_receiver %>
        <% sum = 0 %>
        <% convs_sender.each do |conv| %>
          <% sum += conv.sender_notifications %>
        <% end %>
        <% convs_receiver.each do |conv| %>
          <% sum += conv.receiver_notifications %>
        <% end %>


<!--        Searhc drop was here before <li class="create-post bar">|</li> -->



        <li class="nav-item dropdown">
          <% if current_user.prof_pic.attached? %>

            <div style="position:relative">

              <% if sum > 0 %>
                <div class="nav-badge badge"><%= sum %></div>
              <% else %>
                <div class="nav-badge badge" style="display: none;">0</div>
              <% end %>


            </div>
            <%= cl_image_tag current_user.prof_pic.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          <% else %>
            <%= image_tag "https://res.cloudinary.com/ddclrx1ajasdf/image/upload/v1614812119/placeholder_avatar/1200px-Avatar_icon_green.svg_tire2w.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right  drop-nav" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", profile_path(current_user), class: "dropdown-item" %>
            <div style="position:relative"><%= link_to "Messages", conversations_path, class: "dropdown-item" %>

              <% if sum > 0 %>
                <div class="msg-dropdown-badge badge"><%= sum %></div>
              <% else %>
                <div class="msg-dropdown-badge badge" style="display: none;">0</div>
              <% end %>

            </div>
            <%= link_to "My Posts", posts_path, class: "dropdown-item" %>
            <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-links">
          <%= link_to "Login", new_user_session_path %>
           | <%= link_to "Sign Up", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
    </div>
  </div>

</div>

app/views/shared/_postcards.html.erb
  <% @posts.each do |post| %>
    <%= link_to(post_path(post)) do %>
      <div class="w-100 post-view">
        <div class="col-8 post-resume">

          <div class="post-content">

            <div class="post-top">
              <span class="post-headline">
                <h3><%= post.title.truncate(70) %></h3>
              </span>
              <span class="rating" id="stars"><%= render "/shared/stars", rating: post.current_rating[:avg] %>
                <span id="views">(<%= post.ratings.count %>)</span>
              </span>
            </div>


            <div class="post-text">
              <p><%= truncate(post.rich_body.to_plain_text.squish, length: 250)  %></p>
            </div>

            <span class="user-info">
              <p><%= post.user == current_user ? "You" : post.user.nickname %> - <%= post.created_at.strftime("%b %e, %l:%M%p") %></p>
              <%= cl_image_tag post.user.prof_pic.key, class:"avatar-card" %>
            </span>
          </div>
        </div>
          <% if post.photos.attached? %>
            <div class="post-img col-4 post-img" style="background-image: url(<%= cl_image_path post.photos.last.key %>);"></div>
          <% else %>
            <div class="post-img col-4 post-img" style="background-image: url(https://res.cloudinary.com/ddclrx1ajasdf/image/upload/v1614952509/post_seeds/pexels-pixabay-56875_cdviyq.jpg);"></div>
          <% end %>
      </div>
    <% end %>
 <% end %>

app/views/shared/_postcards_OLD.html.erb
  <% @posts.each do |post| %>
    <div class="w-100 post-view">
      <div class="col-8 post-resume">

        <div class="post-content">
          <div class="user-data">
            <%= cl_image_tag post.user.prof_pic.key, class:"avatar-bordered" %>
            <p>Posted by <%= post.user.nickname %> </p>
            <span class="rating" id="stars"><%= render "/shared/stars", rating: post.current_rating[:avg] %>
              <span id="views">(<%= post.ratings.count %>)</span>
            </span>
          </div>
          <div class="container post-text">
          <h3>"<%= post.title %>"</h3>
          <p>
            <%= truncate(post.rich_body.to_plain_text.squish, length: 250)  %>
          </p>
          </div>
          <div class="btn-panel-container">
              <%= link_to "View", post_path(post), class:"btn-panel"%>

              <% if current_user == post.user %>
                <%= link_to "Edit", edit_post_path(post), class:"btn-panel" %>
                <%= link_to "Delete", post_path(post), method: :delete, class:"btn-panel" %>
              <% end %>
          </div>
        </div>
      </div>
        <% if post.photos.attached? %>
        <div class="post-img col-4 post-img" style="background-image: url(<%= cl_image_path post.photos.last.key %>);"></div>
        <% else %>
        <div class="post-img col-4 post-img" style="background-image: url(https://res.cloudinary.com/ddclrx1ajasdf/image/upload/v1614952509/placeholder_avatar/pexels-pixabay-56875_cdviyq.jpg);"></div>
        <% end %>
    </div>
 <% end %>

app/views/shared/_searchbar.html.erb
<div class="search-cont">
  <div class="search-input-group">
      <div class="search-input col-7">
        <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :query, params[:query], placeholder: "Find a post" %>
      </div>
      <div class="cat-sub col-5">
        <div class= "drop-list">
          <%= select_tag "category", options_for_select(%w[all hack don't project], \
          selected: params[:category]), id: "search-field", :include_blank => "Category" %>
        </div>
         <div class= "drop-list">
          <%= select_tag :ratings, options_for_select([["overall rating", "rating_avg"], ["co2","rating_co2"], ["waste","rating_waste"], ["resources","rating_resources"], ["DIY effort","rating_diyeffort"], ["eco cost","rating_ecocost"],["Latest","created_at"]], \
          selected: params[:ratings]), id: "search-field", :include_blank => "Sort by"%>
        </div>
        <div class= "submit-btn">
          <%= submit_tag "Go", class: "search-bar-submit btn", reset: true %>
        </div>
        <% end %>
      </div>
  </div>
</div>

app/views/shared/_sortby.html.erb
<div class="filters">
  <ul class="w-100">
    <li class="filter-btn">Sort by:</li>
    <li class="filter-btn"> <%= link_to "Rating", search_path(query:"sort_by_avg_rating") %> </li>
    <li class="filter-btn"> <%= link_to "Views", search_path(query:"sort_by_views_count") %> </li>
    <li class="filter-btn"> <%= link_to "CO2", search_path(query:"CO_2_sort_by_rating") %> </li>
    <li class="filter-btn"> <%= link_to "Waste reduction", search_path(query:"waste_sort_by_rating") %> </li>
    <li class="filter-btn"> <%= link_to "Resource saving", search_path(query:"resource_sort_by_rating") %> </li>
    <li class="filter-btn"> <%= link_to "Ease of use", search_path(query:"diy_sort_by_rating") %> </li>
    <li class="filter-btn"> <%= link_to "Free of side-effects", search_path(query:"cost_sort_by_rating") %> </li>
  </ul>
</div>
<!-- This action is not working properly and has been commented in posts_controller search -->

app/views/shared/_stars.html.erb
<% green = rating.round %>
<% grey = 5 - green %>
<span class="rating-post">
  <% green.times do |x| %>
    <span class="tree-green">&#x1F333;</span>
<!--     <i class="fas fa-star star-green"></i> -->
  <% end %>
  <% grey.times do |x| %>
    <span class="tree-grey">&#x1F333;</span>
  <% end %>
</span>